name: immich-mediakit
services:
  immich-mediakit:
    container_name: immich-mediakit
    hostname: immich-mediakit
    restart: unless-stopped
    ports:
      - ${MKIT_PORT:-8086}:8086
    volumes:
      - ${MKIT_DATA}/data:/app/data
      - ${MKIT_DATA}/cache:/root/.cache/torch/
      - ./src:/app/src:ro  # Dev Only
    env_file:
      - .env
    environment:
      - DASH_DEBUG=${DASH_DEBUG:-false}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qdrant
      - redis
    healthcheck:
      test: sh -c "curl -f http://localhost:${MKIT_PORT:-8086}/ || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    container_name: immich-mediakit-qdrant
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - ${QDRANT_PORT:-6333}:6333
    volumes:
      - ${MKIT_DATA}/qdrant:/qdrant/storage

  redis:
    container_name: immich-mediakit-redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ${MKIT_DATA}/redis:/data
    command: redis-server --save 60 1 --loglevel warning
