name: Feature Request
description: Suggest a new feature or enhancement for Immich-MediaKit
title: "[Feature] "
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe what you'd like to see.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature you'd like...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Mockups, examples, or other helpful information
      placeholder: Screenshots, similar features in other tools, etc.
    validations:
      required: false
