
#------------------------------------------------
# Example Immich docker-compose.yml configuration
#
# WARNING: This is the same-host version
#------------------------------------------------
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

  immich-machine-learning:
    container_name: immich_ml
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    # ports:
    #   - "5433:5432"
#------------------------------------------------
# Modification 1: Add networks to enable communication with immich-mediakit
#------------------------------------------------
    networks:
      - immich-mediakit
      #------------------------------------------------
      # Note: On some Docker environments, you might need to add '- default' to keep
      # the database in both the default network and immich-mediakit network.
      # This ensures other Immich services can still connect to the database.
      # See: https://github.com/RazgrizHsu/immich-mediakit/issues/30
      #------------------------------------------------
      # - default  # Uncomment if Immich services cannot connect to the database

#------------------------------------------------
# Modification 2: Add global networks section to declare external network usage
#------------------------------------------------
networks:
  immich-mediakit:
    external: true
  #------------------------------------------------
  # Note: On some Docker environments, you might need to add '- default' to keep
  # the database in both the default network and immich-mediakit network.
  # This ensures other Immich services can still connect to the database.
  # See: https://github.com/RazgrizHsu/immich-mediakit/issues/30
  #------------------------------------------------
  #default  # Uncomment if Immich services cannot connect to the database
