
#------------------------------------------------
# Example Immich docker-compose.yml modifications for same-host setup
#
# IMPORTANT: This file only shows the parts you need to pay attention to.
# Use your official Immich docker-compose.yml and apply these modifications.
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# WARNING: This is the same-host version
#------------------------------------------------
name: immich
services:
  immich-server:
    container_name: immich_server
    volumes:
      # For Immich >= 2.0 (use this if you're on Immich 2.0 or later):
      - ${UPLOAD_LOCATION}:/data
      # For Immich < 2.0 (comment the line above and uncomment this if you're on older Immich):
      # - ${UPLOAD_LOCATION}:/usr/src/app/upload

  immich-machine-learning:
    container_name: immich_ml

  redis:
    container_name: immich_redis

  database:
    container_name: immich_postgres
    # ports:
    #   - "5433:5432"
#------------------------------------------------
# Modification 1: Add networks to enable communication with immich-mediakit
#------------------------------------------------
    networks:
      - immich-mediakit
      #------------------------------------------------
      # Note: On some Docker environments, you might need to add '- default' to keep
      # the database in both the default network and immich-mediakit network.
      # This ensures other Immich services can still connect to the database.
      # See: https://github.com/RazgrizHsu/immich-mediakit/issues/30
      #------------------------------------------------
      # - default  # Uncomment if Immich services cannot connect to the database

#------------------------------------------------
# Modification 2: Add global networks section to declare external network usage
#------------------------------------------------
networks:
  immich-mediakit:
    external: true
  #------------------------------------------------
  # Note: On some Docker environments, you might need to add '- default' to keep
  # the database in both the default network and immich-mediakit network.
  # This ensures other Immich services can still connect to the database.
  # See: https://github.com/RazgrizHsu/immich-mediakit/issues/30
  #------------------------------------------------
  #default  # Uncomment if Immich services cannot connect to the database
