
#------------------------------------------------
# Example Immich docker-compose.yml modifications for different-host setup
#
# IMPORTANT: This file only shows the parts you need to pay attention to.
# Use your official Immich docker-compose.yml and apply these modifications.
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# WARNING: This is the different-host version
#------------------------------------------------
name: immich
services:
  immich-server:
    container_name: immich_server
    volumes:
      # For Immich >= 2.0 (use this if you're on Immich 2.0 or later):
      - ${UPLOAD_LOCATION}:/data
      # For Immich < 2.0 (comment the line above and uncomment this if you're on older Immich):
      # - ${UPLOAD_LOCATION}:/usr/src/app/upload

  immich-machine-learning:
    container_name: immich_ml

  redis:
    container_name: immich_redis

  database:
    container_name: immich_postgres
#------------------------------------------------
# Modification 1: Expose database port for external access
#------------------------------------------------
    ports:
      - "5432:5432"
