name: immich-mediakit
services:
  immich-mediakit:
    container_name: immich-mediakit
    hostname: immich-mediakit
    image: razgrizhsu/immich-mediakit:latest
    restart: unless-stopped
    ports:
      - ${MKIT_PORT:-8086}:8086
    volumes:
      - ${MKIT_DATA}:/app/data                  # mediakit data
      - ${MKIT_DATA}/cache:/root/.cache/torch/  # model cache
      - ${IMMICH_PATH}:/immich:ro               # Read-only access to Immich photos
    env_file:
      - .env
    environment:
      - DASH_DEBUG=${DASH_DEBUG:-false}
      - IMMICH_PATH=/immich                     # Override path inside container

    # GPU Support (Linux + NVIDIA GPU only)
    # To enable NVIDIA GPU acceleration:
    # 1. Change image tag to razgrizhsu/immich-mediakit:latest-cuda
    # 2. Uncomment the deploy configuration below
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    depends_on:
      - qdrant
    healthcheck:
      test: sh -c "curl -f http://localhost:${MKIT_PORT:-8086}/ || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - immich-mediakit

  qdrant:
    container_name: immich-mediakit-qdrant
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - ${QDRANT_PORT:-6333}:6333
    volumes:
      - ${MKIT_DATA}/qdrant:/qdrant/storage
    networks:
      - immich-mediakit

networks:
  immich-mediakit:
    driver: bridge
